presubmits:
  kubernetes-sigs/aws-encryption-provider:
  - name: pull-aws-encryption-provider-verify
    decorate: true
    always_run: true
    max_concurrency: 5
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master
        command:
        - runner.sh
        args:
        - make
        - lint
        env:
        - name: GO111MODULE
          value: "on"
    annotations:
      testgrid-dashboards: provider-aws-encryption-provider
      testgrid-tab-name: verify
      description: aws-encryption-provider verification
      testgrid-num-columns-recent: '30'
  - name: pull-aws-encryption-provider-unittest
    decorate: true
    always_run: true
    max_concurrency: 5
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master
        command:
        - runner.sh
        args:
        - make
        - test
        - build-server
        - TAG=$PULL_PULL_SHA
        env:
        - name: GO111MODULE
          value: "on"
    annotations:
      testgrid-dashboards: provider-aws-encryption-provider
      testgrid-tab-name: unit-test
      description: aws-encryption-provider unit tests
      testgrid-num-columns-recent: '30'
