presubmits:
  kubernetes/kops:
  - name: pull-kops-build
    skip_branches:
    - release-1.23
    - release-1.22
    always_run: true
    skip_report: false
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 40m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "version-dist"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: build
  - name: pull-kops-test
    skip_branches:
    - release-1.23
    - release-1.22
    always_run: true
    skip_report: false
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "test"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: test
  - name: pull-kops-e2e-kubernetes-do-gossip
    branches:
    - master
    always_run: false
    labels:
      preset-service-account: "true"
      preset-do-credential: "true"
      preset-do-spaces-credential: "true"
      preset-do-ssh: "true"
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        imagePullPolicy: Always
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
            make test-e2e-install
            kubetest2 kops \
            -v 2 \
            --up --build --down \
            --cloud-provider=digitalocean \
            --cluster-name=e2e-test-do.k8s.local \
            --env S3_ENDPOINT=sfo3.digitaloceanspaces.com \
            --env JOB_NAME=pull-kops-e2e-kubernetes-do-gossip \
            --create-args "--networking=calico --api-loadbalancer-type=public --node-count=2 --master-count=3" \
            --kubernetes-version=https://dl.k8s.io/release/stable.txt \
            --kops-binary-path=/home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops \
            --test=kops \
            -- \
            --test-package-marker=stable.txt \
            --parallel 25
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "3Gi"
          requests:
            cpu: "2"
            memory: "3Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e-do-gossip
  - name: pull-kops-e2e-kubernetes-do-fqdn
    branches:
    - master
    always_run: false
    labels:
      preset-service-account: "true"
      preset-do-credential: "true"
      preset-do-spaces-credential: "true"
      preset-do-ssh: "true"
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 90m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        imagePullPolicy: Always
        command:
        - runner.sh
        args:
        - bash
        - -c
        - |
            make test-e2e-install
            kubetest2 kops \
            -v 2 \
            --up --build --down \
            --cloud-provider=digitalocean \
            --cluster-name=e2e-b284d3e83b-4c77c.test-cncf-do.k8s.io \
            --env S3_ENDPOINT=sfo3.digitaloceanspaces.com \
            --env JOB_NAME=pull-kops-e2e-kubernetes-do-fqdn \
            --create-args "--networking=calico --node-count=2" \
            --kubernetes-version=https://dl.k8s.io/release/stable.txt \
            --kops-binary-path=/home/prow/go/src/k8s.io/kops/.build/dist/linux/amd64/kops \
            --test=kops \
            -- \
            --test-package-marker=stable.txt \
            --parallel 25
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "3Gi"
          requests:
            cpu: "2"
            memory: "3Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: e2e-do-kubetest2
  - name: pull-kops-verify-generated
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-generate"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-generated
  - name: pull-kops-verify-gomod
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-gomod"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-gomod
  - name: pull-kops-verify-boilerplate
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-boilerplate"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-boilerplate
  - name: pull-kops-verify-gofmt
    branches:
    - master
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-gofmt"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-gofmt
  - name: pull-kops-verify-gofmt-go118
    branches:
    - release-1.24
    - release-1.23
    - release-1.22
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        command:
        - runner.sh
        args:
        - "make"
        - "verify-gofmt"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-gofmt-go118
  - name: pull-kops-verify-govet
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "govet"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-govet
  - name: pull-kops-verify-golangci-lint
    branches:
      - master
    always_run: true
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 15m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-golangci-lint"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-golangci-lint
  - name: pull-kops-verify-hashes
    skip_report: false
    run_if_changed: '^upup\/pkg\/fi\/cloudup\/(containerd|docker)'
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 10m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-hashes"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-hashes
  - name: pull-kops-verify-terraform
    skip_report: false
    run_if_changed: '^tests\/integration\/update_cluster\/'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "verify-terraform"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, presubmits-kops, kops-presubmits
      testgrid-tab-name: verify-terraform
postsubmits:
  kubernetes/kops:
  - name: kops-postsubmit
    branches:
    - master
    labels:
      preset-service-account: "true"
    decorate: true
    decoration_config:
      timeout: 25m
    path_alias: k8s.io/kops
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - "make"
        - "prow-postsubmit"
        - "UPLOAD_DEST=gs://k8s-release-dev/kops/ci"
        resources:
          requests:
            memory: "2Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-kops, kops-presubmits
