# sigs.k8s.io/kwok presubmits
presubmits:
  kubernetes-sigs/kwok:
  - name: pull-kwok-verify-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-verify-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - verify
  - name: pull-kwok-build-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-build-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - build
  - name: pull-kwok-unit-test-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-unit-test-main
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
  - name: pull-kwok-e2e-test-main
    decorate: true
    path_alias: sigs.k8s.io/kwok
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kwok-e2e-test-main
    labels:
      preset-dind-enabled: "true"
    branches:
    - ^main$
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - e2e-test
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
