presets:
- labels:
    preset-capz-windows-common-124: "true"
  env:
  - name: "KUBERNETES_VERSION"
    value: "latest-1.24"
  - name: E2E_ARGS
    value: "-kubetest.use-ci-artifacts"
  - name: WINDOWS
    value: "true"
  - name: TEST_WINDOWS #temp to unblock failing jobs on windows while we fix this in capz (https://github.com/kubernetes/kubernetes/issues/116474)
    value: "true"
  - name: AZURE_NODE_MACHINE_TYPE
    value: "Standard_D4s_v3"
periodics:
- name: ci-kubernetes-e2e-capz-master-containerd-windows-1-24
  interval: 24h
  decorate: true
  decoration_config:
    timeout: 4h0m0s
  labels:
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true" # Sets REGISTRY which is needed when building CCM/CNM images
    preset-capz-containerd-1-6-latest: "true"
    preset-capz-windows-2019: "true"
    preset-capz-windows-common-124: "true"
    preset-capz-windows-parallel: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    # The Windows 1.24 jobs should stay on CAPZ release-1.6 for now because later versions build CNM and CCM
    # images from k-sigs/cluster-provider-azure repo and the container image builds are not working.
    base_ref: release-1.6
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    workdir: true
  spec:
    containers:
    - command:
      - runner.sh
      - ./scripts/ci-conformance.sh
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
      name: ""
      resources:
        requests:
          cpu: "2"
          memory: 9Gi
      securityContext:
        privileged: true
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    testgrid-dashboards: sig-release-1.24-informing, sig-windows-1.24-release, sig-windows-signal
    testgrid-tab-name: capz-windows-containerd-1.24
- name: ci-kubernetes-e2e-capz-master-containerd-windows-serial-slow-1-24
  interval: 24h
  decorate: true
  decoration_config:
    timeout: 4h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true" # Sets REGISTRY which is needed when building CCM/CNM images
    preset-capz-windows-common-124: "true"
    preset-capz-windows-2019: "true"
    preset-capz-containerd-1-6-latest: "true"
    preset-capz-serial-slow: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-azure
    # The Windows 1.24 jobs should stay on CAPZ release-1.6 for now because later versions build CNM and CCM
    # images from k-sigs/cluster-provider-azure repo and the container image builds are not working.
    base_ref: release-1.6
    path_alias: sigs.k8s.io/cluster-api-provider-azure
    workdir: true
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        securityContext:
          privileged: true
        env:
        # Skip tests that require etcd image for 1.24 Windows jobs because the etcd image referenced in this branch does not container Windows images.
        - name: GINKGO_SKIP
          value: \[LinuxOnly\]|\[Serial\]|\[Slow\]|\[alpha\]|GMSA|Guestbook.application.should.create.and.stop.a.working.application|device.plugin.for.Windows|Aggregator.Should.be.able.to.support.the.1.17.Sample.API.Server|be.restarted.with.a.GRPC.liveness.probe
        resources:
          requests:
            cpu: 2
            memory: "9Gi"
  annotations:
    testgrid-alert-email: kubernetes-provider-azure@googlegroups.com, sig-windows-leads@kubernetes.io
    testgrid-dashboards: sig-windows-1.24-release
    testgrid-tab-name: capz-windows-containerd-serial-slow-1.24
