presubmits:
  kubernetes/cloud-provider-vsphere:

  - name: pull-cloud-provider-vsphere-verify-fmt-1-26-minus
    cluster: eks-prow-build-cluster
    always_run: false
    run_if_changed: '\.go$|hack/check-format\.sh'
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - make
        args:
        - fmt
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
      testgrid-tab-name: pr-verify-fmt-1-26-minus
      description: Verifies the Golang sources have been formatted

  - name: pull-cloud-provider-vsphere-verify-lint-1-26-minus
    cluster: eks-prow-build-cluster
    always_run: false
    run_if_changed: '\.go$|hack/check-lint\.sh'
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - make
        args:
        - lint
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
      testgrid-tab-name: pr-verify-lint-1-26-minus
      description: Verifies the Golang sources are linted

  - name: pull-cloud-provider-vsphere-verify-vet-1-26-minus
    cluster: eks-prow-build-cluster
    always_run: false
    run_if_changed: '\.go$|hack/check-vet\.sh'
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - make
        args:
        - vet
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
      testgrid-tab-name: pr-verify-vet-1-26-minus
      description: Vets the Golang sources have been vetted

  - name: pull-cloud-provider-vsphere-verify-staticcheck-1-26-minus
    cluster: eks-prow-build-cluster
    always_run: false
    run_if_changed: '\.go$|hack/check-staticcheck\.sh$|go.mod'
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - make
        args:
        - staticcheck
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
      testgrid-tab-name: pr-verify-staticheck-1-26-minus
      description: Verifies the Golang sources pass a static source checker

  # Builds the CCM and CSI binaries.
  - name: pull-cloud-provider-vsphere-build-1-26-minus
    cluster: eks-prow-build-cluster
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    skip_submodules: true
    always_run: false
    run_if_changed: '\.go$|go.mod'
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - "make"
        args:
        - "build"
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com

  # Executes the unit tests.
  - name: pull-cloud-provider-vsphere-unit-test-1-26-minus
    cluster: eks-prow-build-cluster
    decorate: true
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    skip_submodules: true
    always_run: false
    run_if_changed: '\.go$|go.mod'
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - "make"
        args:
        - "unit-test"
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com

  # Executes the integration tests.
  - name: pull-cloud-provider-vsphere-integration-test-1-26-minus
    cluster: eks-prow-build-cluster
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    skip_submodules: true
    always_run: false
    run_if_changed: '\.go$|go.mod'
    skip_report: false
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - "make"
        args:
        - "integration-test"
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com

  # Executes the test coverage.
  - name: pull-cloud-provider-vsphere-coverage-1-26-minus
    cluster: eks-prow-build-cluster
    always_run: true
    decorate: true
    path_alias: k8s.io/cloud-provider-vsphere
    branches:
    - ^release-1.2[4-6]$
    extra_refs:
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - runner.sh
        - bash
        args:
        - -c
        - |
          result=0
          ./scripts/ci-test-coverage.sh || result=$?
          cp coverage.* ${ARTIFACTS}
          cd ../../k8s.io/test-infra/gopherage
          GO111MODULE=on go build .
          ./gopherage filter --exclude-path="zz_generated,generated\.go" "${ARTIFACTS}/coverage.out" > "${ARTIFACTS}/filtered.cov" || result=$?
          ./gopherage html "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/coverage.html" || result=$?
          ./gopherage junit --threshold 0 "${ARTIFACTS}/filtered.cov" > "${ARTIFACTS}/junit_coverage.xml" || result=$?
          exit $result
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
      testgrid-tab-name: pr-verify-test-coverage-1-26-minus
      description: Shows the test coverage of the Golang sources

  # Executes the e2e tests.
  - name: pull-cloud-provider-vsphere-e2e-test-1-26-minus
    decorate: true
    labels:
      preset-dind-enabled: "true"
      # Borrows CAPV credentials for cloud provider e2e testing
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cloud-provider-vsphere-e2e-config: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - ^release-1.2[4-6]$
    path_alias: k8s.io/cloud-provider-vsphere
    skip_submodules: true
    always_run: false
    run_if_changed: '\.go$|go.mod|hack/e2e\.sh|test/e2e/'
    skip_report: false
    optional: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        command:
        - runner.sh
        args:
        - ./hack/e2e.sh
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "4000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-presubmits-cloud-provider-vsphere, presubmits-cloud-provider-vsphere-blocking
      testgrid-alert-email: k8s-testing-cloud-provider-vsphere+alerts@groups.vmware.com
