dashboards:
- dashboard_tab:
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-hypershift-v4.13-sanity-aws-hypershift-rosa-install
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-hypershift-v4.13-sanity-aws-hypershift-rosa-install
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-addon-v4.13-smoke-rosa-rhods
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-addon-v4.13-smoke-rosa-rhods
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-sanity-rosa-rhods-gpu-servicemesh
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-sanity-rosa-rhods-gpu-servicemesh
  - base_options: width=10&exclude-filter-by-regex=Monitor%5Cscluster&exclude-filter-by-regex=%5Eoperator.Run%20template.*container%20test%24
    code_search_path: https://github.com/openshift/origin/search
    code_search_url_template:
      url: https://github.com/openshift/origin/compare/<start-custom-0>...<end-custom-0>
    file_bug_template:
      options:
      - key: classification
        value: Red Hat
      - key: product
        value: OpenShift Container Platform
      - key: cf_internal_whiteboard
        value: buildcop
      - key: short_desc
        value: 'test: <test-name>'
      - key: cf_environment
        value: 'test: <test-name>'
      - key: comment
        value: 'test: <test-name> failed, see job: <link>'
      url: https://bugzilla.redhat.com/enter_bug.cgi
    name: periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift
    open_bug_template:
      url: https://github.com/openshift/origin/issues/
    open_test_template:
      url: https://prow.ci.openshift.org/view/gs/<gcs_prefix>/<changelist>
    results_url_template:
      url: https://prow.ci.openshift.org/job-history/<gcs_prefix>
    test_group_name: periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift
  name: redhat-openshift-CSPI-QE-MSI-release-4.13-informing
test_groups:
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-hypershift-v4.13-sanity-aws-hypershift-rosa-install
  name: periodic-ci-CSPI-QE-MSI-hypershift-v4.13-sanity-aws-hypershift-rosa-install
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-addon-v4.13-smoke-rosa-rhods
  name: periodic-ci-CSPI-QE-MSI-rhods-addon-v4.13-smoke-rosa-rhods
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-sanity-rosa-rhods-gpu-servicemesh
  name: periodic-ci-CSPI-QE-MSI-rhods-gpu-servicemesh-operators-v4.13-sanity-rosa-rhods-gpu-servicemesh
- gcs_prefix: origin-ci-test/logs/periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift
  name: periodic-ci-CSPI-QE-MSI-rhods-operator-v4.13-sanity-rosa-rhods-hypershift
