periodics:
- cron: "0 4-23/12 * * *"
  name: ci-kubernetes-e2e-gce-gpu-stable2-stable1-cluster-upgrade
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=180
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8 --ginkgo.skip=\[.+\]|Initializers|Dashboard
      - --timeout=150m
      - --upgrade_args=--ginkgo.focus=\[Feature:GPUClusterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master

  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-gpu-stable2-stable1-cluster-upgrade
    description: upgrade from HEAD of stable2 branch to HEAD of stable1 branch
- cron: "0 5-23/12 * * *"
  name: ci-kubernetes-e2e-gce-gpu-stable2-stable1-master-upgrade
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=180
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8 --ginkgo.skip=\[.+\]|Initializers|Dashboard
      - --timeout=150m
      - --upgrade_args=--ginkgo.focus=\[Feature:GPUMasterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master

  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-gpu-stable2-stable1-master-upgrade
    description: upgrade from HEAD of stable2 branch to HEAD of stable1 branch

- cron: "0 3-23/12 * * *"
  name: ci-kubernetes-e2e-gce-gpu-stable1-latest-cluster-upgrade
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=180
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8 --ginkgo.skip=\[.+\]|Initializers|Dashboard
      - --timeout=150m
      - --upgrade_args=--ginkgo.focus=\[Feature:GPUClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master

  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-gpu-stable1-latest-cluster-upgrade
    description: upgrade from HEAD of stable1 branch to HEAD of master branch
- cron: "0 9-23/12 * * *"
  name: ci-kubernetes-e2e-gce-gpu-stable1-latest-master-upgrade
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
    preset-ci-gce-device-plugin-gpu: "true"
  spec:
    containers:
    - args:
      - --timeout=180
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8 --ginkgo.skip=\[.+\]|Initializers|Dashboard
      - --timeout=150m
      - --upgrade_args=--ginkgo.focus=\[Feature:GPUMasterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master

  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-gpu-stable1-latest-master-upgrade
    description: upgrade from HEAD of stable1 branch to HEAD of master branch
