periodics:
- name: ci-ingress-nginx-e2e-main
  interval: 12h
  max_concurrency: 1
  path_alias: k8s.io/ingress-nginx
  decorate: true
  decoration_config:
    timeout: 1h
  extra_refs:
  - org: kubernetes
    repo: ingress-nginx
    base_ref: main
    path_alias: k8s.io/ingress-nginx
  skip_submodules: true
  labels:
    preset-kind-volume-mounts: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/krte:v20220121-bb77a9cb93-master
      command:
        - wrapper.sh
        - bash
        - -c
        - curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && make kind-e2e-test
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      env:
      - name: REPO_INFO
        value: https://github.com/kubernetes/ingress-nginx
  annotations:
    testgrid-dashboards: sig-network-ingress-nginx
    testgrid-tab-name: ci-e2e-main
    testgrid-num-columns-recent: '20'
