presets:
  - labels:
      preset-e2e-containerd-ec2: "true"
    env:
      - name: KUBE_BUILD_PLATFORMS
        value: linux/amd64
      - name: AWS_REGION
        value: us-east-1
      - name: SSH_USER
        value: ec2-user
      - name: DELETE_INSTANCES
        value: "true"
periodics:
  - name: ci-cgroupv1-containerd-node-e2e-ec2
    interval: 12h
    annotations:
      testgrid-dashboards: sig-node-containerd
      testgrid-tab-name: cgroupv1-containerd-node-e2e-ec2
      testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    labels:
      preset-e2e-containerd-ec2: "true"
    cluster: eks-prow-build-cluster
    decorate: true
    extra_refs:
      - org: kubernetes-sigs
        repo: provider-aws-test-infra
        base_ref: main
        path_alias: sigs.k8s.io/provider-aws-test-infra
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: node-e2e-tests
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
          command:
            - runner.sh
          args:
            - hack/make-rules/test-e2e-node.sh
          env:
            - name: FOCUS
              value: \[NodeConformance\]
            - name: TEST_ARGS
              value: '--container-runtime-process-name=containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          resources:
            limits:
              cpu: 8
              memory: 10Gi
            requests:
              cpu: 8
              memory: 10Gi
  - name: ci-kubernetes-node-arm64-e2e-containerd-ec2
    interval: 12h
    annotations:
      testgrid-dashboards: sig-node-containerd
      testgrid-tab-name: ci-kubernetes-node-arm64-e2e-containerd-ec2
      testgrid-alert-email: kubernetes-sig-node-test-failures@googlegroups.com
    labels:
      preset-e2e-containerd-ec2: "true"
      preset-dind-enabled: "true"
    cluster: eks-prow-build-cluster
    decorate: true
    extra_refs:
      - org: kubernetes-sigs
        repo: provider-aws-test-infra
        base_ref: main
        path_alias: sigs.k8s.io/provider-aws-test-infra
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: node-e2e-tests
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
          command:
            - runner.sh
          args:
            - hack/make-rules/test-e2e-node.sh
          env:
            - name: FOCUS
              value: NodeConformance
            - name: USE_DOCKERIZED_BUILD
              value: "true"
            - name: TARGET_BUILD_ARCH
              value: "linux/arm64"
            - name: IMAGE_CONFIG_FILE
              value: aws-instance-arm64.yaml
            - name: TEST_ARGS
              value: '--container-runtime-process-name=/usr/bin/containerd --container-runtime-pid-file= --kubelet-flags="--runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 8
              memory: 10Gi
            requests:
              cpu: 8
              memory: 10Gi
  - name: ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2
    interval: 12h
    annotations:
      testgrid-dashboards: sig-node-containerd
      testgrid-tab-name: ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2
    labels:
      preset-e2e-containerd-ec2: "true"
      preset-dind-enabled: "true"
    cluster: eks-prow-build-cluster
    decorate: true
    extra_refs:
      - org: kubernetes-sigs
        repo: provider-aws-test-infra
        base_ref: main
        path_alias: sigs.k8s.io/provider-aws-test-infra
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: node-e2e-tests
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
          command:
            - runner.sh
          args:
            - hack/make-rules/test-e2e-node.sh
          env:
            - name: FOCUS
              value: \[Serial\]
            - name: SKIP
              value: \[Flaky\]|\[Benchmark\]|\[NodeSpecialFeature:.+\]|\[NodeSpecialFeature\]|\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]|\[NodeFeature:Eviction\]
            - name: USE_DOCKERIZED_BUILD
              value: "true"
            - name: TARGET_BUILD_ARCH
              value: "linux/arm64"
            - name: IMAGE_CONFIG_FILE
              value: aws-instance-arm64.yaml
            - name: TEST_ARGS
              value: '--kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          # docker-in-docker needs privileged mode
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 8
              memory: 10Gi
            requests:
              cpu: 8
              memory: 10Gi
  - name: ci-cgroupv1-containerd-node-e2e-serial-ec2
    interval: 12h
    annotations:
      testgrid-dashboards: sig-node-containerd
      testgrid-tab-name: ci-cgroupv1-containerd-node-e2e-serial-ec2
    labels:
      preset-e2e-containerd-ec2: "true"
    cluster: eks-prow-build-cluster
    decorate: true
    extra_refs:
      - org: kubernetes-sigs
        repo: provider-aws-test-infra
        base_ref: main
        path_alias: sigs.k8s.io/provider-aws-test-infra
      - org: kubernetes
        repo: kubernetes
        base_ref: master
        path_alias: k8s.io/kubernetes
    spec:
      serviceAccountName: node-e2e-tests
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
          command:
            - runner.sh
          args:
            - hack/make-rules/test-e2e-node.sh
          env:
            - name: FOCUS
              value: \[Serial\]
            - name: SKIP
              value: \[Flaky\]|\[Benchmark\]|\[NodeSpecialFeature:.+\]|\[NodeSpecialFeature\]|\[NodeAlphaFeature:.+\]|\[NodeAlphaFeature\]|\[NodeFeature:Eviction\]
            - name: TEST_ARGS
              value: '--kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd*\"]}"'
          resources:
            limits:
              cpu: 8
              memory: 10Gi
            requests:
              cpu: 8
              memory: 10Gi
