# sigs.k8s.io/kube-scheduler-simulator presubmits
presubmits:
  kubernetes-sigs/kube-scheduler-simulator:
  - name: pull-kube-scheduler-simulator-backend-lint
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kube-scheduler-simulator-backend-lint
    decorate: true
    path_alias: sigs.k8s.io/kube-scheduler-simulator
    branches:
    - ^master$
    always_run: false
    spec:
      containers:
      - image: golang:1.17
        command:
        - /bin/bash
        - -c
        - >
          make mod-download &&
          make tools &&
          export PATH="${PATH}:${GOPATH}/bin" &&
          make lint
  - name: pull-kube-scheduler-simulator-frontend-lint
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-kube-scheduler-simulator-frontend-lint
    decorate: true
    path_alias: sigs.k8s.io/kube-scheduler-simulator
    branches:
    - ^master$
    always_run: false
    spec:
      containers:
      - image: node:16
        command:
        - /bin/bash
        - -c
        - >
          cd ./web &&
          yarn install --frozen-lockfile &&
          yarn run lint
