presubmits:
  kubernetes-sigs/cluster-api-provider-ibmcloud:
  - name: pull-cluster-api-provider-ibmcloud-make
    always_run: true
    branches:
      # The script this job runs is not in all branches.
      - ^main$
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-ibmcloud
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - command:
        - "runner.sh"
        - "./scripts/ci-make.sh"
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.23
        imagePullPolicy: Always
        resources:
          requests:
            memory: "6Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-ibmcloud
      testgrid-tab-name: pr-make
  - name: pull-cluster-api-provider-ibmcloud-test
    always_run: true
    branches:
      # The script this job runs is not in all branches.
      - ^main$
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-ibmcloud
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.23
        imagePullPolicy: Always
        command:
        - "./scripts/ci-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-ibmcloud
      testgrid-tab-name: pr-test
  - name: pull-cluster-api-provider-ibmcloud-build
    always_run: true
    branches:
      # The script this job runs is not in all branches.
      - ^main$
    optional: false
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-ibmcloud
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.23
        command:
        - "./scripts/ci-build.sh"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-ibmcloud
      testgrid-tab-name: pr-build
  - name: pull-cluster-api-provider-ibmcloud-verify
    always_run: true
    branches:
      # The script this job runs is not in all branches.
      - ^main$
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-ibmcloud"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.23
          command:
            - "make"
            - "verify"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-ibmcloud
      testgrid-tab-name: pr-verify
