presubmits:
  kubernetes-csi/csi-driver-smb:
  - name: pull-csi-driver-smb-verify
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        args:
        - make
        - verify
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-verify
      description: "Run code verification tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-unit
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        args:
        - make
        - unit-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-unit
      description: "Run unit tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-sanity
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        args:
        - make
        - sanity-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-sanity
      description: "Run sanity tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-integration
    decorate: true
    always_run: false
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        args:
        - make
        - integration-test
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-integration
      description: "Run integration tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-windows-build
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        args:
        - make
        - smb-windows
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-windows-build
      description: "Run make smb-windows for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-e2e
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.19
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/test/e2e/manifest/linux.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        # Specific test args
        - --test-csi-driver-smb
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-e2e
      description: "Run E2E tests for SMB CSI driver on VMAS cluster."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-e2e-vmss
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.20
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/test/e2e/manifest/linux-vmss.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        # Specific test args
        - --test-csi-driver-smb
        securityContext:
          privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-e2e-vmss
      description: "Run E2E tests for SMB CSI driver on VMSS cluster."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-e2e-windows
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.19
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/test/e2e/manifest/windows.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        # Specific test args
        - --test-csi-driver-smb
        securityContext:
          privileged: true
        env:
          - name: TEST_WINDOWS
            value: "true"
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-e2e-windows
      description: "Run Windows E2E tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-e2e-windows-containerd
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-azure-windows: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --build=quick
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.19
        - --aksengine-public-key=$(K8S_SSH_PUBLIC_KEY_PATH)
        - --aksengine-private-key=$(K8S_SSH_PRIVATE_KEY_PATH)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/test/e2e/manifest/containerd-windows.json
        - --aksengine-download-url=https://aka.ms/aks-engine/aks-engine-k8s-e2e.tar.gz
        # Specific test args
        - --test-csi-driver-smb
        securityContext:
          privileged: true
        env:
          - name: TEST_WINDOWS
            value: "true"
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-e2e-windows-containerd
      description: "Run Windows containerd E2E tests for SMB CSI driver."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-external-e2e
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-azure-cred: "true"
      preset-dind-enabled: "true"
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
      workdir: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        command:
        - runner.sh
        - kubetest
        args:
        # Generic e2e test args
        - --test
        - --up
        - --down
        - --dump=$(ARTIFACTS)
        # Azure-specific test args
        - --provider=skeleton
        - --deployment=aksengine
        - --aksengine-admin-username=azureuser
        - --aksengine-creds=$(AZURE_CREDENTIALS)
        - --aksengine-orchestratorRelease=1.22
        - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
        - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/test/e2e/manifest/external.json
        - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
        # Specific test args
        - --test-csi-driver-smb
        securityContext:
          privileged: true
        env:
          - name: EXTERNAL_E2E_TEST
            value: "true"
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-external-e2e
      description: "Run External E2E tests for SMB CSI driver on VMAS cluster."
      testgrid-num-columns-recent: '30'
  - name: pull-csi-driver-smb-e2e-gce
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/csi-driver-smb
    branches:
    - master
    labels:
      preset-k8s-ssh: "true"
      preset-service-account: "true"
      preset-common-gce-windows: "true"
      preset-e2e-gce-windows: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --cluster=
        - --env=KUBE_MASTER_OS_DISTRIBUTION=cos
        - --env=KUBE_GCE_MASTER_IMAGE=cos-89-16108-470-11
        - --env=KUBE_GCE_MASTER_PROJECT=cos-cloud
        - --env=KUBE_NODE_OS_DISTRIBUTION=cos
        - --env=KUBE_GCE_NODE_IMAGE=cos-89-16108-470-11
        - --env=KUBE_GCE_NODE_PROJECT=cos-cloud
        - --env=KUBE_WINDOWS_CONTAINER_RUNTIME=containerd
        - --env=KUBERNETES_NODE_PLATFORM=windows
        - --extract=ci/latest
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=8
        - --provider=gce
        - --gcp-nodes=2
        - --test=false
        - --test-cmd=$GOPATH/src/sigs.k8s.io/csi-driver-smb/test/run-e2e-test.sh
        - --timeout=120m
        env:
        - name: WINDOWS_NODE_OS_DISTRIBUTION
          value: "win2019"
        - name: PREPULL_YAML
          value: "prepull-head.yaml"
        - name: REGISTRY
          value: "k8s.gcr.io/e2e-test-images"
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
        securityContext:
            privileged: true
    annotations:
      testgrid-dashboards: sig-storage-csi-other
      testgrid-tab-name: pull-csi-driver-smb-e2e-gce
      description: "Run E2E tests for SMB CSI driver on GCE cluster."
