presubmits:
  kubernetes-sigs/cluster-api-provider-aws:
  - name: pull-cluster-api-provider-aws-test
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
        command:
        - "./scripts/ci-test.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-test
  - name: pull-cluster-api-provider-aws-build
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
        command:
        - "./scripts/ci-build.sh"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-build
  - name: pull-cluster-api-provider-aws-verify
    always_run: true
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
        command:
        - "make"
        - "verify"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-verify
  # conformance test
  - name: pull-cluster-api-provider-aws-e2e-conformance
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    extra_refs:
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
          command:
            - "runner.sh"
            - "./scripts/ci-conformance.sh"
          env:
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
            - name: AWS_REGION
              value: "us-west-2"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              # these are both a bit below peak usage during build
              # this is mostly for building kubernetes
              memory: "9Gi"
              cpu: 2
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-conformance
      testgrid-num-columns-recent: '20'
  # conformance test against kubernetes main branch with `kind` + cluster-api-provider-aws
  - name: pull-cluster-api-provider-aws-e2e-conformance-with-ci-artifacts
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
          command:
            - "runner.sh"
            - "./scripts/ci-conformance.sh"
          env:
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
            - name: AWS_REGION
              value: "us-west-2"
            - name: E2E_ARGS
              value: "-kubetest.use-ci-artifacts"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-conformance-main-k8s-main
      testgrid-num-columns-recent: '20'
  - name: pull-cluster-api-provider-aws-e2e-blocking
    branches:
      # The script this job runs is not in all branches.
      - ^main$
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    #run_if_changed: '^((api|bootstrap|cmd|config|controllers|controlplane|exp|feature|hack|pkg|test|util)/|main\.go|go\.mod|go\.sum|Dockerfile|Makefile)'
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          env:
            - name: E2E_FOCUS
              value: "\\[PR-Blocking\\]"
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
            - name: AWS_REGION
              value: "us-west-2"
            # Parallelize tests
            - name: GINKGO_ARGS
              value: "-nodes 20"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-quick-e2e-main
      testgrid-num-columns-recent: '20'
  - name: pull-cluster-api-provider-aws-e2e
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          env:
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
            - name: AWS_REGION
              value: "us-west-2"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-e2e-main
      testgrid-num-columns-recent: '20'
  - name: pull-cluster-api-provider-aws-e2e-eks
    branches:
    # The script this job runs is not in all branches.
    - ^main$
    path_alias: "sigs.k8s.io/cluster-api-provider-aws"
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-service-account: "true"
      preset-aws-ssh: "true"
      preset-aws-credential: "true"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211210-0c6ec8feca-master
          command:
            - "runner.sh"
            - "./scripts/ci-e2e-eks.sh"
          env:
            - name: BOSKOS_HOST
              value: "boskos.test-pods.svc.cluster.local"
            - name: AWS_REGION
              value: "us-west-2"
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 2
              memory: "9Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-aws
      testgrid-tab-name: pr-e2e-eks-main
      testgrid-num-columns-recent: '20'
