presubmits:
  kubernetes-sigs/kubetest2:
  - name: pull-kubetest2-verify
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - verify
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
        securityContext:
          privileged: true
  - name: pull-kubetest2-build
    cluster: eks-prow-build-cluster
    decorate: true
    always_run: true
    labels:
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - make
        - build-all
        resources:
          limits:
            cpu: 1
            memory: 4Gi
          requests:
            cpu: 1
            memory: 4Gi
        securityContext:
          privileged: true
