presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gci-gce-autoscaling
    annotations:
      testgrid-dashboards: sig-autoscaling-cluster-autoscaler
      testgrid-tab-name: gci-gce-autoscaling-pull
    always_run: false
    optional: true
    run_if_changed: '^(cluster/gce/manifests/cluster-autoscaler.manifest$|cluster/addons/rbac/cluster-autoscaler)'
    labels:
      preset-pull-kubernetes-e2e: "true"
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --job=$(JOB_NAME)
        - --repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)
        - --repo=k8s.io/release
        - --service-account=/etc/service-account/service-account.json
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=450
        - --scenario=kubernetes_e2e
        - --
        - --build=quick
        - --cluster=
        # Override GCE default for cluster size autoscaling purposes.
        - --env=ENABLE_CUSTOM_METRICS=true
        - --env=KUBE_ENABLE_CLUSTER_AUTOSCALER=true
        - --env=KUBE_AUTOSCALER_MIN_NODES=3
        - --env=KUBE_AUTOSCALER_MAX_NODES=6
        - --env=KUBE_AUTOSCALER_ENABLE_SCALE_DOWN=true
        - --env=KUBE_ADMISSION_CONTROL=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota,Priority
        - --env=ENABLE_POD_PRIORITY=true
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-nodes=3
        - --gcp-project=k8s-jkns-gci-autoscaling
        - --gcp-zone=us-west1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gci-gce-autoscaling
        - --runtime-config=scheduling.k8s.io/v1alpha1=true
        - --test_args=--ginkgo.focus=\[Feature:ClusterSizeAutoscalingScaleUp\]|\[Feature:ClusterSizeAutoscalingScaleDown\]|\[Feature:InitialResources\] --ginkgo.skip=\[Flaky\] --minStartupPods=8
        - --timeout=400m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master
        securityContext:
          privileged: true

  - name: pull-kubernetes-e2e-autoscaling-hpa-cpu
    annotations:
      testgrid-dashboards: sig-autoscaling-hpa
      testgrid-tab-name: gci-gce-autoscaling-hpa-cpu-pull
    # TODO: set `optional: false` once tests not flaky
    optional: true
    decorate: true
    decoration_config:
      timeout: 310m
    run_if_changed: '^(pkg\/controller\/podautoscaler\/|test\/e2e\/autoscaling\/horizontal_pod_autoscaling|test\/e2e\/framework\/autoscaling\/)'
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --check-leaked-resources
        - --provider=gce
        - --gcp-zone=us-west1-b
        - --gcp-node-image=gci
        # Enable HPAContainerMetrics. Required for container metrics tests.
        - --env=KUBE_FEATURE_GATES=HPAContainerMetrics=true
        - --extract=ci/latest
        - --test_args=--ginkgo.focus=\[Feature:HPA\] --minStartupPods=8
        - --ginkgo-parallel=1
        - --timeout=300m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master

  - name: pull-kubernetes-e2e-autoscaling-hpa-cm
    annotations:
      testgrid-dashboards: sig-autoscaling-hpa
      testgrid-tab-name: gci-gce-autoscaling-hpa-cm-pull
    # TODO: set `optional: false` once tests not flaky
    optional: true
    decorate: true
    decoration_config:
      timeout: 310m
    run_if_changed: '^(pkg\/controller\/podautoscaler\/|test\/e2e\/autoscaling\/custom_metrics_stackdriver_autoscaling.go$)'
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - command:
        - runner.sh
        - /workspace/scenarios/kubernetes_e2e.py
        args:
        - --cluster=hpa
        - --extract=ci/latest
        - --gcp-node-image=gci
        - --gcp-project=k8s-jkns-gci-autoscaling
        - --gcp-zone=us-west1-b
        - --provider=gce
        # Enable HPAContainerMetrics and HPAScaleToZero. Required for container metrics and scale to zero tests.
        - --env=KUBE_FEATURE_GATES=HPAContainerMetrics=true,HPAScaleToZero=true
        - --test_args=--ginkgo.focus=\[Feature:CustomMetricsAutoscaling\] --ginkgo.skip=\[Flaky\] --minStartupPods=8
        - --timeout=300m
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master
