periodics:
# GCE upgrades
- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-cluster
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-cluster-parallel
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\]
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-cluster-new
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/latest --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-cluster-new-parallel
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-master
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 2h
  name: ci-kubernetes-e2e-gce-stable1-latest-upgrade-master-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/latest
      - --extract=ci/k8s-stable1
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --ginkgo-parallel
      - --provider=gce
      - --test_args=--ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/latest
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable1-latest-upgrade-master-parallel
    description: upgrade from HEAD of stable1 branch to HEAD of master branch

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-cluster
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable2-stable1-upgrade-cluster
    description: upgrade from HEAD of stable2 branch to HEAD of stable1 branch

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-cluster-new
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --skew
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:ClusterUpgrade\] --upgrade-target=ci/k8s-stable1 --upgrade-image=gci
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable2-stable1-upgrade-cluster-new
    description: upgrade from HEAD of stable2 branch to HEAD of stable1 branch

- interval: 12h
  name: ci-kubernetes-e2e-gce-stable2-stable1-upgrade-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=920
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --env=STORAGE_MEDIA_TYPE=application/vnd.kubernetes.protobuf
      - --extract=ci/k8s-stable1
      - --extract=ci/k8s-stable2
      - --gcp-node-image=gci
      - --gcp-zone=us-west1-b
      - --provider=gce
      - --test_args=--kubectl-path=../../../../kubernetes_skew/cluster/kubectl.sh --minStartupPods=8
      - --timeout=900m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --upgrade-target=ci/k8s-stable1
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
  annotations:
    testgrid-dashboards: google-gce-upgrade
    testgrid-tab-name: gce-stable2-stable1-upgrade-master
    description: upgrade from HEAD of stable2 branch to HEAD of stable1 branch
