presubmits:
  kubernetes-sigs/cluster-api-provider-gcp:
  - name: pull-cluster-api-provider-gcp-test-v1beta1
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
      - ^release-1.0$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master
        command:
        - "./scripts/ci-test.sh"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-test-release-v1beta1
  - name: pull-cluster-api-provider-gcp-build-v1beta1
    always_run: true
    optional: false
    decorate: true
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
      - ^release-1.0$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master
        command:
        - "./scripts/ci-build.sh"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-build-release-v1beta1
  - name: pull-cluster-api-provider-gcp-make-release-v1beta1
    always_run: true
    optional: false
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
      - ^release-1.0$
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
        command:
        - "runner.sh"
        - "./scripts/ci-make.sh"
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-make-release-v1beta1
  - name: pull-cluster-api-provider-gcp-e2e-test-release-v1beta1
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
      - ^release-1.0$
    always_run: true
    optional: false
    decorate: true
    decoration_config:
      timeout: 3h
    extra_refs:
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              # these are both a bit below peak usage during build
              # this is mostly for building kubernetes
              memory: "9000Mi"
              # during the tests more like 3-20m is used
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-e2e-test-release-v1beta1
  - name: pull-cluster-api-provider-gcp-make-conformance-release-v1beta1
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
      - ^release-1.0$
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.22
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
          command:
            - "runner.sh"
            - "./scripts/ci-conformance.sh"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              # these are both a bit below peak usage during build
              # this is mostly for building kubernetes
              memory: "9000Mi"
              # during the tests more like 3-20m is used
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-conformance-release-v1beta1
  - name: pull-cluster-api-provider-gcp-conformance-ci-artifacts-release-v1beta1
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
    - ^release-1.0$
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 3h
    extra_refs:
    - org: kubernetes-sigs
      repo: image-builder
      base_ref: master
      path_alias: "sigs.k8s.io/image-builder"
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-master
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: E2E_ARGS
              value: "-kubetest.use-ci-artifacts"
            - name: USE_CI_ARTIFACTS
              value: "true"
          command:
            - "runner.sh"
            - "./scripts/ci-conformance.sh"
            - "--init-image"
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
          resources:
            requests:
              # these are both a bit below peak usage during build
              # this is mostly for building kubernetes
              memory: "9000Mi"
              # during the tests more like 3-20m is used
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-conformance-ci-artifacts-release-v1beta1
  - name: pull-cluster-api-provider-gcp-capi-e2e-release-v1beta1
    labels:
      preset-service-account: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
    branches:
    - ^release-1.0$
    always_run: false
    optional: true
    decorate: true
    decoration_config:
      timeout: 3h
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220124-681f3531ec-1.22
          env:
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
            - name: GINKGO_FOCUS
              value: "Cluster API E2E tests"
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          securityContext:
            privileged: true
          resources:
            requests:
              memory: "9000Mi"
              cpu: 2000m
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
      testgrid-tab-name: pr-capi-e2e-release-v1beta1
