periodics:
- name: periodic-cluster-api-provider-gcp-build-release-1-2
  interval: 4h
  decorate: true
  cluster: eks-prow-build-cluster
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: release-1.2
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
      command:
      - "runner.sh"
      - "./scripts/ci-build.sh"
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 4
          memory: 4Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: capg-build-release-1-2
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-gcp-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-gcp-test-release-1-2
  interval: 4h
  decorate: true
  cluster: eks-prow-build-cluster
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: release-1.2
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
      args:
      - "runner.sh"
      - "./scripts/ci-test.sh"
      resources:
        limits:
          cpu: 4
          memory: 4Gi
        requests:
          cpu: 4
          memory: 4Gi
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: capg-test-release-1-2
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-gcp-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "2"
- name: periodic-cluster-api-provider-gcp-conformance-release-1-2
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  decorate: true
  decoration_config:
    timeout: 3h
  interval: 12h
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api-provider-gcp
    base_ref: release-1.2
    path_alias: "sigs.k8s.io/cluster-api-provider-gcp"
  spec:
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        env:
          - name: "BOSKOS_HOST"
            value: "boskos.test-pods.svc.cluster.local"
        command:
          - "runner.sh"
          - "./scripts/ci-conformance.sh"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            # these are both a bit below peak usage during build
            # this is mostly for building kubernetes
            memory: "9000Mi"
            # during the tests more like 3-20m is used
            cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-gcp
    testgrid-tab-name: capg-conformance-release-release-1-2
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-gcp-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "5"
