# manifest list tests
periodics:
- name: periodic-kubernetes-e2e-manifest-lists
  cluster: eks-prow-build-cluster
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=60
      - --repo=k8s.io/kubeadm=main
      - --scenario=execute
      - --
      - ./tests/e2e/manifests/verify_manifest_lists.sh
      image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
      resources:
        limits:
          memory: "9000Mi"
          cpu: 2000m
        requests:
          memory: "9000Mi"
          cpu: 2000m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-all
    testgrid-tab-name: periodic-manifest-lists
    testgrid-alert-email: sig-cluster-lifecycle-kubeadm-alerts@kubernetes.io
    description: "OWNER: sig-cluster-lifecycle; an e2e test for verifying manifest list images at registry.k8s.io"
    testgrid-num-columns-recent: "20"
    testgrid-num-failures-to-alert: "2"
    testgrid-alert-stale-results-hours: "48"
