presubmits:
  kubernetes-sigs/cloud-provider-azure:
    - name: pull-cloud-provider-azure-check-1-21
      always_run: true
      decorate: true
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
            command:
              - runner.sh
            args:
              - make
              - test-check
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-check-1-21
        description: "Run lint check tests for cloud-provider-azure release-1.0."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-1-21 runs kubernetes conformance tests.
    - name: pull-cloud-provider-azure-e2e-1-21
      always_run: true
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
        preset-azure-cred: "true"
        preset-dind-enabled: "true"
      extra_refs:
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.21
          path_alias: k8s.io/kubernetes
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-1.21
            command:
              - runner.sh
              - kubetest
            args:
              # Generic e2e test args
              - --test
              - --up
              - --down
              - --build=quick
              - --dump=$(ARTIFACTS)
              # Azure-specific test args
              - --provider=skeleton
              - --deployment=aksengine
              - --aksengine-agentpoolcount=2
              - --aksengine-admin-username=azureuser
              - --aksengine-creds=$(AZURE_CREDENTIALS)
              - --aksengine-orchestratorRelease=1.21
              - --aksengine-mastervmsize=Standard_DS2_v2
              - --aksengine-agentvmsize=Standard_D4s_v3
              - --aksengine-ccm
              - --aksengine-cnm
              - --aksengine-deploy-custom-k8s
              - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
              - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux.json
              - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
              # Specific test args
              - --test_args=--ginkgo.focus=\[Conformance\]|\[NodeConformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Flaky\]
              - --ginkgo-parallel=30
            securityContext:
              privileged: true
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-1-21
        description: "Run Kubernetes e2e tests for cloud-provider-azure release-1.0."
        testgrid-num-columns-recent: '30'
    # pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-21 runs Azure specific e2e tests with VMSS and basic loadbalancer.
    - name: pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-21
      always_run: true
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
        preset-azure-cred: "true"
        preset-dind-enabled: "true"
      extra_refs:
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.21
          path_alias: k8s.io/kubernetes
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-1.21
            command:
              - runner.sh
              - kubetest
            args:
              # Generic e2e test args
              - --test
              - --up
              - --down
              - --build=quick
              - --dump=$(ARTIFACTS)
              # Azure-specific test args
              - --provider=skeleton
              - --deployment=aksengine
              - --aksengine-agentpoolcount=2
              - --aksengine-admin-username=azureuser
              - --aksengine-creds=$(AZURE_CREDENTIALS)
              - --aksengine-orchestratorRelease=1.21
              - --aksengine-mastervmsize=Standard_DS2_v2
              - --aksengine-agentvmsize=Standard_D4s_v3
              - --aksengine-ccm
              - --aksengine-cnm
              - --aksengine-deploy-custom-k8s
              - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
              - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-vmss-basic-lb.json
              - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
              # Specific test args
              - --test-ccm
              - --ginkgo-parallel=30
            securityContext:
              privileged: true
            env:
              - name: AZURE_LOADBALANCER_SKU
                value: "basic"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-21
        description: "Runs Azure specific tests (VMSS + basic LB) with cloud-provider-azure release-1.0 (https://github.com/kubernetes-sigs/cloud-provider-azure)."
        testgrid-num-columns-recent: '30'
      # pull-cloud-provider-azure-e2e-ccm-1-21
    - name: pull-cloud-provider-azure-e2e-ccm-1-21
      always_run: true
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
        preset-azure-cred: "true"
        preset-dind-enabled: "true"
      extra_refs:
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.21
          path_alias: k8s.io/kubernetes
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-1.21
            command:
              - runner.sh
              - kubetest
            args:
              # Generic e2e test args
              - --test
              - --up
              - --down
              - --build=quick
              - --dump=$(ARTIFACTS)
              # Azure-specific test args
              - --provider=skeleton
              - --deployment=aksengine
              - --aksengine-agentpoolcount=2
              - --aksengine-admin-username=azureuser
              - --aksengine-creds=$(AZURE_CREDENTIALS)
              - --aksengine-orchestratorRelease=1.21
              - --aksengine-mastervmsize=Standard_DS2_v2
              - --aksengine-agentvmsize=Standard_D4s_v3
              - --aksengine-ccm
              - --aksengine-cnm
              - --aksengine-deploy-custom-k8s
              - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
              - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux.json
              - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
              # Specific test args
              - --test-ccm
              - --ginkgo-parallel=30
            securityContext:
              privileged: true
            env:
              - name: AZURE_LOADBALANCER_SKU
                value: "standard"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-1-21
        description: "Runs Azure specific tests with cloud-provider-azure release-1.0 (https://github.com/kubernetes-sigs/cloud-provider-azure)."
        testgrid-num-columns-recent: '30'
      # pull-cloud-provider-azure-e2e-ccm-vmss-1-21
    - name: pull-cloud-provider-azure-e2e-ccm-vmss-1-21
      always_run: true
      decorate: true
      decoration_config:
        timeout: 5h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
        preset-azure-cred: "true"
        preset-dind-enabled: "true"
      extra_refs:
        - org: kubernetes
          repo: kubernetes
          base_ref: release-1.21
          path_alias: k8s.io/kubernetes
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-1.21
            command:
              - runner.sh
              - kubetest
            args:
              # Generic e2e test args
              - --test
              - --up
              - --down
              - --build=quick
              - --dump=$(ARTIFACTS)
              # Azure-specific test args
              - --provider=skeleton
              - --deployment=aksengine
              - --aksengine-agentpoolcount=2
              - --aksengine-admin-username=azureuser
              - --aksengine-creds=$(AZURE_CREDENTIALS)
              - --aksengine-orchestratorRelease=1.21
              - --aksengine-mastervmsize=Standard_DS2_v2
              - --aksengine-agentvmsize=Standard_D4s_v3
              - --aksengine-ccm
              - --aksengine-cnm
              - --aksengine-deploy-custom-k8s
              - --aksengine-public-key=$(AZURE_SSH_PUBLIC_KEY_FILE)
              - --aksengine-template-url=https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/tests/k8s-azure/manifest/linux-vmss.json
              - --aksengine-download-url=https://github.com/Azure/aks-engine/releases/download/nightly/aks-engine-nightly-linux-amd64.tar.gz
              # Specific test args
              - --test-ccm
              - --ginkgo-parallel=30
            securityContext:
              privileged: true
            env:
              - name: AZURE_LOADBALANCER_SKU
                value: "standard"
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-vmss-1-21
        description: "Runs Azure specific tests with cloud-provider-azure release-1.0 (https://github.com/kubernetes-sigs/cloud-provider-azure)."
        testgrid-num-columns-recent: '30'
    - name: pull-cloud-provider-azure-e2e-ccm-capz-1-21
      always_run: true
      optional: true
      decorate: true
      decoration_config:
        timeout: 3h
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-dind-enabled: "true"
        preset-kind-volume-mounts: "true"
        preset-azure-cred-only: "true"
        preset-azure-anonymous-pull: "true"
      extra_refs:
        - org: kubernetes-sigs
          repo: cluster-api-provider-azure
          base_ref: release-1.0
          path_alias: sigs.k8s.io/cluster-api-provider-azure
          workdir: true
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-1.21
            command:
            - runner.sh
            - ./scripts/ci-entrypoint.sh
            args:
            - bash
            - -c
            - >-
              cd ${GOPATH}/src/sigs.k8s.io/cloud-provider-azure &&
              make test-ccm-e2e
            securityContext:
              privileged: true
            env:
              - name: TEST_CCM
                value: "true"
              - name: AZURE_LOADBALANCER_SKU
                value: "standard"
              - name: KUBERNETES_VERSION
                value: 1.21.5
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-e2e-ccm-capz-1-21
        description: "Runs Azure specific tests with cloud-provider-azure release-1.0 (https://github.com/kubernetes-sigs/cloud-provider-azure) using cluster-api-provider-azure."
        testgrid-num-columns-recent: '30'
    - name: pull-cloud-provider-azure-unit-1-21
      always_run: true
      decorate: true
      path_alias: sigs.k8s.io/cloud-provider-azure
      branches:
        - release-1.0
      labels:
        preset-service-account: "true"
      spec:
        containers:
          - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211217-ea95cec1d4-master
            command:
              - runner.sh
            args:
              - make
              - test-unit
      annotations:
        testgrid-dashboards: provider-azure-cloud-provider-azure-1-21-presubmit
        testgrid-tab-name: pr-cloud-provider-azure-unit-1-21
        description: "Run unit tests for cloud-provider-azure release-1.0."
        testgrid-num-columns-recent: '30'
