periodics:
- name: periodic-cluster-api-test-release-1-3
  interval: 4h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.3
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
      command:
      - "./scripts/ci-test.sh"
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.3
    testgrid-tab-name: capi-test-release-1-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-test-mink8s-release-1-3
  interval: 4h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.3
    path_alias: sigs.k8s.io/cluster-api
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
      command:
      - "./scripts/ci-test.sh"
      env:
      # This value determines the minimum Kubernetes
      # supported version for Cluster API management cluster.
      #
      # To check the available envtest in Kubebuilder, please
      # refer to https://github.com/kubernetes-sigs/kubebuilder/tree/tools-releases.
      - name: KUBEBUILDER_ENVTEST_KUBERNETES_VERSION
        value: "1.20.2"
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.3
    testgrid-tab-name: capi-test-mink8s-release-1-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-release-1-3
  interval: 4h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.3
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
        args:
          - runner.sh
          - "./scripts/ci-e2e.sh"
        env:
          - name: GINKGO_SKIP
            value: "\\[Conformance\\] \\[K8s-Upgrade\\]|\\[IPv6\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.3
    testgrid-tab-name: capi-e2e-release-1-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
- name: periodic-cluster-api-e2e-mink8s-release-1-3
  interval: 4h
  decorate: true
  decoration_config:
    gcs_credentials_secret: "" # Use workload identity for uploading artifacts
  rerun_auth_config:
    github_team_slugs:
    - org: kubernetes-sigs
      slug: cluster-api-maintainers
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
  extra_refs:
  - org: kubernetes-sigs
    repo: cluster-api
    base_ref: release-1.3
    path_alias: sigs.k8s.io/cluster-api
  - org: kubernetes
    repo: kubernetes
    base_ref: master
    path_alias: k8s.io/kubernetes
  spec:
    serviceAccountName: prowjob-default-sa
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.25
      args:
      - runner.sh
      - "./scripts/ci-e2e.sh"
      env:
      - name: GINKGO_SKIP
        value: "\\[Conformance\\] \\[K8s-Upgrade\\]|\\[IPv6\\]"
      # This value determines the minimum Kubernetes
      # supported version for Cluster API management cluster.
      # Because of that we usually would test with v1.20, but because ClusterClass
      # requires at least 1.22 we are using 1.22 instead.
      # Note: We need ClusterClass for the clusterctl upgrade tests, so we're able to
      # create clusterctl with old versions with the right cgroupDriver configuration.
      - name: KUBERNETES_VERSION_MANAGEMENT
        value: "v1.22.17"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 7300m
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-1.3
    testgrid-tab-name: capi-e2e-mink8s-release-1-3
    testgrid-alert-email: sig-cluster-lifecycle-cluster-api-alerts@kubernetes.io
    testgrid-num-failures-to-alert: "4"
