presubmits:
  kubernetes-sigs/cluster-api-provider-vsphere:
  - name: pull-cluster-api-provider-vsphere-verify-lint-release-1-4
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.4$
    always_run: false
    run_if_changed: '^((api|cmd|config|contrib|controllers|pkg)/|Makefile|hack/check-lint\.sh)'
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        command:
        - hack/check-lint.sh
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: pr-verify-lint-release-1-4
      testgrid-alert-email: k8s-testing-clusterapi-vsphere+alerts@groups.vmware.com
      description: Verifies the Golang sources are linted

  - name: pull-cluster-api-provider-vsphere-test-release-1-4
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.4$
    always_run: false
    run_if_changed: '^((api|cmd|config|contrib|controllers|pkg|test)/|Makefile|go\.mod|go\.sum|main\.go)'
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        resources:
          requests:
            cpu: "500m"
        command:
        - runner.sh
        args:
        - make
        - test
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: pr-test-release-1-4
      testgrid-alert-email: k8s-testing-clusterapi-vsphere+alerts@groups.vmware.com
      description: Runs unit tests

  - name: pull-cluster-api-provider-vsphere-integration-test-release-1-4
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    always_run: false
    run_if_changed: '^((api|cmd|config|contrib|controllers|pkg|test)/|Makefile|go\.mod|go\.sum|main\.go)'
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.4$
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
          # we need privileged mode in order to do docker in docker
          securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              cpu: "4000m"
              memory: "6Gi"
          command:
            - runner.sh
          args:
            - make
            - test-integration
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: pr-test-integration-release-1-4
      testgrid-alert-email: k8s-testing-clusterapi-vsphere+alerts@groups.vmware.com
      description: Runs integration tests

  - name: pull-cluster-api-provider-vsphere-e2e-release-1-4
    branches:
      - ^release-1.4$
    labels:
      preset-dind-enabled: "true"
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cluster-api-provider-vsphere-gcs-creds: "true"
      preset-kind-volume-mounts: "true"
    always_run: false
    run_if_changed: '^((api|cmd|config|contrib|controllers|packaging|pkg|test)/|Dockerfile|Makefile|hack/e2e\.sh|go\.mod|go\.sum|main\.go)'
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    max_concurrency: 3
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        command:
        - runner.sh
        args:
        - ./hack/e2e.sh
        env:
        - name: GINKGO_FOCUS
          value: "\\[PR-Blocking\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          requests:
            cpu: "4000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: pr-e2e-release-1-4
      testgrid-alert-email: k8s-testing-clusterapi-vsphere+alerts@groups.vmware.com
      description: Runs only PR Blocking e2e tests

  - name: pull-cluster-api-provider-vsphere-full-e2e-release-1-4
    branches:
      - ^release-1.4$
    labels:
      preset-dind-enabled: "true"
      preset-cluster-api-provider-vsphere-e2e-config: "true"
      preset-cluster-api-provider-vsphere-gcs-creds: "true"
      preset-kind-volume-mounts: "true"
    always_run: false
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-vsphere
    max_concurrency: 3
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.24
        command:
        - runner.sh
        args:
        - ./hack/e2e.sh
        env:
        - name: GINKGO_SKIP
          value: "\\[clusterctl-Upgrade\\] \\[specialized-infra\\] \\[Conformance\\]"
        # we need privileged mode in order to do docker in docker
        securityContext:
          privileged: true
          capabilities:
            add: ["NET_ADMIN"]
        resources:
          requests:
            cpu: "4000m"
            memory: "6Gi"
    annotations:
      testgrid-dashboards: vmware-cluster-api-provider-vsphere, sig-cluster-lifecycle-cluster-api-provider-vsphere
      testgrid-tab-name: pr-full-e2e-release-1-4
      testgrid-alert-email: k8s-testing-clusterapi-vsphere+alerts@groups.vmware.com
      description: Runs all e2e tests
