presubmits:
  containerd/containerd:
  - name: pull-containerd-build
    always_run: true
    branches:
    - main
    - release/1.6
    - release/1.7
    decorate: true
    annotations:
      testgrid-dashboards: sig-node-containerd,containerd-presubmits
      testgrid-tab-name: pull-containerd-build
      description: build artifacts
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        - runner.sh
        args:
        - ./test/build.sh
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true

  - name: pull-containerd-node-e2e
    always_run: true
    max_concurrency: 8
    decorate: true
    branches:
    - main
    decoration_config:
      timeout: 100m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    annotations:
      testgrid-dashboards: sig-node-containerd,containerd-presubmits
      testgrid-tab-name: pull-containerd-node-e2e
      description: run node e2e tests
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - name: pull-containerd-node-e2e
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        env:
        - name: USE_TEST_INFRA_LOG_DUMPING
          value: "true"
        command:
        - sh
        - -c
        - >
          runner.sh
          ./test/build.sh
          &&
          cd ${GOPATH}/src/k8s.io/kubernetes
          &&
          /workspace/scenarios/kubernetes_e2e.py
          --deployment=node
          --gcp-project=cri-c8d-pr-node-e2e
          --gcp-zone=us-central1-f
          '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          --node-tests=true
          --provider=gce
          '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:.+\]|\[NodeFeature\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"'
          --timeout=65m
          "--node-args=--image-config-file=${GOPATH}/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-main-presubmit/image-config-presubmit.yaml -node-env=PULL_REFS=$(PULL_REFS)"

  - name: pull-containerd-node-e2e-1-7
    always_run: true
    max_concurrency: 8
    decorate: true
    branches:
    - release/1.7
    decoration_config:
      timeout: 100m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    annotations:
      testgrid-dashboards: sig-node-containerd,containerd-presubmits
      testgrid-tab-name: pull-containerd-node-e2e-1-7
      description: run node e2e tests
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - name: pull-containerd-node-e2e
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        env:
        - name: USE_TEST_INFRA_LOG_DUMPING
          value: "true"
        command:
        - sh
        - -c
        - >
          runner.sh
          ./test/build.sh
          &&
          cd ${GOPATH}/src/k8s.io/kubernetes
          &&
          /workspace/scenarios/kubernetes_e2e.py
          --deployment=node
          --gcp-project=cri-c8d-pr-node-e2e
          --gcp-zone=us-central1-f
          '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          --node-tests=true
          --provider=gce
          '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:.+\]|\[NodeFeature\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"'
          --timeout=65m
          "--node-args=--image-config-file=${GOPATH}/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-release-1.7-presubmit/image-config-presubmit.yaml -node-env=PULL_REFS=$(PULL_REFS)"

  - name: pull-containerd-node-e2e-1-6
    always_run: true
    max_concurrency: 8
    decorate: true
    branches:
    - release/1.6
    decoration_config:
      timeout: 100m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: release-1.26
      path_alias: k8s.io/kubernetes
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    annotations:
      testgrid-dashboards: sig-node-containerd,containerd-presubmits
      testgrid-tab-name: pull-containerd-node-e2e-1-6
      description: run node e2e tests
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - name: pull-containerd-node-e2e-1-6
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        env:
        - name: USE_TEST_INFRA_LOG_DUMPING
          value: "true"
        command:
        - sh
        - -c
        - >
          runner.sh
          ./test/build.sh
          &&
          cd ${GOPATH}/src/k8s.io/kubernetes
          &&
          /workspace/scenarios/kubernetes_e2e.py
          --deployment=node
          --gcp-project=cri-c8d-pr-node-e2e
          --gcp-zone=us-central1-f
          '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          --node-tests=true
          --provider=gce
          '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:.+\]|\[NodeFeature\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"'
          --timeout=65m
          "--node-args=--image-config-file=${GOPATH}/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-release-1.6-presubmit/image-config-presubmit.yaml -node-env=PULL_REFS=$(PULL_REFS)"

  - name: pull-containerd-sandboxed-node-e2e
    always_run: false
    max_concurrency: 8
    decorate: true
    branches:
    - main
    decoration_config:
      timeout: 100m
    extra_refs:
    - org: kubernetes
      repo: kubernetes
      base_ref: master
      path_alias: k8s.io/kubernetes
    - org: kubernetes
      repo: test-infra
      base_ref: master
      path_alias: k8s.io/test-infra
    annotations:
      testgrid-dashboards: sig-node-containerd,containerd-presubmits
      testgrid-tab-name: pull-containerd-sandboxed-node-e2e
      description: run node e2e tests sandboxed
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
    spec:
      containers:
      - name: pull-containerd-node-e2e
        image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        env:
        - name: USE_TEST_INFRA_LOG_DUMPING
          value: "true"
        - name: ENABLE_CRI_SANDBOXES
          value: "sandboxed"
        command:
        - sh
        - -c
        - >
          runner.sh
          ./test/build.sh
          &&
          cd ${GOPATH}/src/k8s.io/kubernetes
          &&
          /workspace/scenarios/kubernetes_e2e.py
          --deployment=node
          --gcp-project=cri-c8d-pr-node-e2e
          --gcp-zone=us-central1-f
          '--node-test-args=--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          --node-tests=true
          --provider=gce
          '--test_args=--nodes=8 --focus="\[NodeConformance\]|\[NodeFeature:.+\]|\[NodeFeature\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]"'
          --timeout=65m
          "--node-args=--image-config-file=${GOPATH}/src/k8s.io/test-infra/jobs/e2e_node/containerd/containerd-main-presubmit/image-config-presubmit.yaml -node-env=PULL_REFS=$(PULL_REFS)"
