presubmits:
  kubernetes-sigs/krm-functions-registry:
  - name: pull-krm-functions-registry-test-master
    decorate: true
    always_run: true
    path_alias: sigs.k8s.io/krm-functions-registry
    branches:
    # The script this job runs is not in all branches.
    - ^master$
    spec:
      containers:
      - image: golang:1.17
        command:
        - ./test.sh
        resources:
          requests:
            cpu: "4000m"
    annotations:
      testgrid-dashboards: sig-cli-misc
      testgrid-tab-name: krm-functions-registry-presubmit-master
      description: krm-functions-registry presubmit tests on master branch
