# sigs.k8s.io/descheduler presubmits
presubmits:
  kubernetes-sigs/descheduler:
  - name: pull-descheduler-verify-release-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-verify-release-1.25
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.25$
    always_run: true
    spec:
      containers:
      - image: golang:1.19.0
        command:
        - make
        args:
        - verify
  - name: pull-descheduler-verify-build-release-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-verify-build-release-1.25
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.25$
    always_run: true
    spec:
      containers:
      - image: golang:1.19.0
        command:
        - make
        args:
        - build
  - name: pull-descheduler-unit-test-release-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-unit-test-release-1.25
    decorate: true
    path_alias: sigs.k8s.io/descheduler
    branches:
    # The script this job runs is not in all branches.
    - ^release-1.25$
    always_run: false
    run_if_changed: '\.go$'
    spec:
      containers:
      - image: golang:1.19.0
        command:
        - make
        args:
        - test-unit
  - name: pull-descheduler-test-e2e-k8s-release-1-25-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-test-e2e-k8s-release-1-25-1.25
    decorate: true
    decoration_config:
      timeout: 20m
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.25
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.25.0"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-descheduler-test-e2e-k8s-release-1-25-1-24
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-test-e2e-k8s-release-1-25-1.24
    decorate: true
    decoration_config:
      timeout: 20m
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.25
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.24.3"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-descheduler-test-e2e-k8s-release-1-25-1-23
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-descheduler-test-e2e-k8s-release-1-25-1.23
    decorate: true
    decoration_config:
      timeout: 20m
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - release-1.25
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.23.4"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
