# sigs.k8s.io/cluster-capacity presubmits
presubmits:
  kubernetes-sigs/cluster-capacity:
  - name: pull-cluster-capacity-verify-gofmt
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.20.3
        command:
        - make
        args:
        - verify-gofmt
  - name: pull-cluster-capacity-verify-build
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.20.3
        command:
        - make
        args:
        - build
  - name: pull-cluster-capacity-unit-test
    decorate: true
    path_alias: sigs.k8s.io/cluster-capacity
    branches:
    # The script this job runs is not in all branches.
    - ^master$
    always_run: true
    spec:
      containers:
      - image: golang:1.20.3
        command:
        - make
        args:
        - test-unit
  - name: pull-cluster-capacity-test-e2e-k8s-master-1-27
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-master-1.27
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.27.1"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-cluster-capacity-test-e2e-k8s-master-1-26
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-master-1.26
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.26.3"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
  - name: pull-cluster-capacity-test-e2e-k8s-master-1-25
    annotations:
      testgrid-dashboards: sig-scheduling
      testgrid-tab-name: pull-cluster-capacity-test-e2e-k8s-master-1.25
    decorate: true
    decoration_config:
      timeout: 20m
    path_alias: sigs.k8s.io/cluster-capacity
    always_run: true
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-master
        command:
        # generic runner script, handles DIND, bazelrc for caching, etc.
        - runner.sh
        env:
        - name: KUBERNETES_VERSION
          value: "v1.25.2"
        - name: KIND_E2E
          value: "true"
        args:
        - make
        - test-e2e
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
