periodics:
- name: periodic-cluster-api-provider-azure-capi-e2e-v1beta1-release-1-8
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.8
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.27
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Cluster API E2E tests"
        - name: GINKGO_SKIP
          value: "\\[K8s-Upgrade\\]|API Version Upgrade"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-capi-e2e-v1beta1-release-1-8
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
- name: periodic-cluster-api-provider-azure-e2e-v1beta1-release-1-8
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.8
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.27
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: "Workload cluster creation"
        - name: GINKGO_SKIP
          value: \[Managed Kubernetes\]
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-v1beta1-release-1-8
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
- name: periodic-cluster-api-provider-azure-e2e-aks-v1beta1-release-1-8
  decorate: true
  decoration_config:
    timeout: 4h
  interval: 72h
  labels:
    preset-dind-enabled: "true"
    preset-kind-volume-mounts: "true"
    preset-azure-cred-only: "true"
    preset-azure-anonymous-pull: "true"
  extra_refs:
    - org: kubernetes-sigs
      repo: cluster-api-provider-azure
      base_ref: release-1.8
      path_alias: "sigs.k8s.io/cluster-api-provider-azure"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230616-e730b60769-1.27
      command:
        - runner.sh
      args:
        - ./scripts/ci-e2e.sh
      env:
        - name: GINKGO_FOCUS
          value: \[Managed Kubernetes\]
        - name: GINKGO_SKIP
          value: ""
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-azure
    testgrid-tab-name: capz-periodic-e2e-aks-v1beta1-release-1-8
    testgrid-alert-email: k8s-infra-staging-cluster-api-azure@kubernetes.io
