periodics:
- name: ci-test-infra-bazel
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 1h
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/launcher.gcr.io/google/bazel:v20210806-38e1be0-test-infra
      command:
      - hack/bazel.sh
      args:
      - test
      - --config=ci
      - --nobuild_tests_only
      - //...
      env:
      - name: BAZEL_FETCH_PLEASE
        value: //...
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: ci-bazel
    description: Runs bazel test //... on the test-infra repo every hour

- name: ci-test-infra-continuous-test
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 1h
  labels:
    # Enable dind for linters that required docker to run, for example typescript.
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20211208-9473f90198-test-infra
      command:
      - runner.sh
      args:
      - make
      - test
      - verify
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: continuous
    description: Runs `make test verify` on the test-infra repo every hour

- name: metrics-kettle
  interval: 1h
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  spec:
    serviceAccountName: triage
    containers:
    - image: gcr.io/k8s-staging-test-infra/bigquery:v20211001-c920b4c552
      args:
      - ./kettle/monitor.py
      - --stale=6
      - --table
      - k8s-gubernator:build.all
      - k8s-gubernator:build.week
      - k8s-gubernator:build.day
  annotations:
    testgrid-num-failures-to-alert: '6'
    testgrid-alert-stale-results-hours: '12'
    testgrid-dashboards: sig-testing-misc
    testgrid-alert-email: kubernetes-sig-testing-alerts@googlegroups.com, k8s-infra-oncall@google.com
    description: Monitors Kettle's BigQuery database freshness.

- name: test-infra-fuzz
  labels:
    preset-dind-enabled: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 1h
  spec:
    serviceAccountName: fuzz-test
    containers:
      #TODO(mpherman) : Change to versioned once stable
    - image: gcr.io/k8s-testimages/ci_fuzz:latest
      command:
        - runner.sh
      args:
        - python3
        - "/opt/oss-fuzz/infra/cifuzz/cifuzz_combined_entrypoint.py"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      env:
      - name: MODE
        value: batch
      - name: REPO_NAME
        value: test-infra
      - name: SANITIZER
        value: 'address'
      - name: CLOUD_BUCKET
        value: gs://prow-cifuzz-test/
      - name: CFL_PLATFORM
        value: prow
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: test-infra-fuzz
    description: Runs clusterfuzzlite every hour

- name: test-infra-cfl-coverage-report
  labels:
    preset-dind-enabled: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 12h
  spec:
    serviceAccountName: fuzz-test
    containers:
      #TODO(mpherman) : Change to versioned once stable
    - image: gcr.io/k8s-testimages/ci_fuzz:latest
      command:
        - runner.sh
      args:
        - python3
        - "/opt/oss-fuzz/infra/cifuzz/cifuzz_combined_entrypoint.py"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      env:
      - name: MODE
        value: coverage
      - name: REPO_NAME
        value: test-infra
      - name: SANITIZER
        value: 'coverage'
      - name: CLOUD_BUCKET
        value: gs://prow-cifuzz-test/
      - name: CFL_PLATFORM
        value: prow
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: test-infra-cfl-coverage-report
    description: Runs clusterfuzzlite coverage report every day

- name: test-infra-cfl-prune
  labels:
    preset-dind-enabled: "true"
  decorate: true
  extra_refs:
  - org: kubernetes
    repo: test-infra
    base_ref: master
  interval: 12h
  spec:
    serviceAccountName: fuzz-test
    containers:
      #TODO(mpherman) : Change to versioned once stable
    - image: gcr.io/k8s-testimages/ci_fuzz:latest
      command:
        - runner.sh
      args:
        - python3
        - "/opt/oss-fuzz/infra/cifuzz/cifuzz_combined_entrypoint.py"
      # docker-in-docker needs privileged mode
      securityContext:
        privileged: true
      env:
      - name: MODE
        value: prune
      - name: REPO_NAME
        value: test-infra
      - name: CLOUD_BUCKET
        value: gs://prow-cifuzz-test/
      - name: CFL_PLATFORM
        value: prow
  annotations:
    testgrid-dashboards: sig-testing-misc
    testgrid-tab-name: test-infra-cfl-prune
    description: Runs clusterfuzzlite corpora prune every day
