name: Build Tide

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Golang caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.4.1

    - name: Auth
      id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1

    - name: Build
      env:
        PROW_REPO_OVERRIDE:  ${{ secrets.PROW_REPO_OVERRIDE }}
        EDGE_PROW_REPO_OVERRIDE: ''
        EDGE_PROW_REPO: ''
      run: |
        ./prow/push-tide.sh


