name: Build Tide

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Setup Golang caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Setup Bazel
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.4.1

    - name: Login to Docker Registry
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | \
        docker login -u ticommunityinfra --password-stdin

    - name: Build
      env:
        PROW_REPO_OVERRIDE:  ${{ secrets.PROW_REPO_OVERRIDE }}
      run: |
        ./prow/push-tide.sh


